eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    name: localhost

microservice:
  payments-service:
    end-points:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/dopayment
  order-service:
    end-points:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  customers-service:
    end-points:
      endpoint:
        uri: http://CUSTOMER-SERVICE/customer/**
